### PR TITLE
Add more vehicles to the simulator

### PR DESCRIPTION
**Pull request by nicolasiensen**
Jira ticket: RSD-605
---
- [x] Add more vehicles so we simulate a fleet of 100
- [x] Add a vehicle driving out of city range

### CODE REVIEW

**Comment by nicolasiensen** [comment]
@adamlukemooney, do you think it is enough to simulate 5 vehicles?

**Comment by adamlukemooney** [comment]
@nicolasiensen In the task we mention 100. I think a larger number is better in order to simulate higher load.

**Comment by nicolasiensen** [comment]
Ok, I think the way I'm generating the routes is not the most optimal, maybe you can help me with that so I don't spend the whole day creating data for all the missing 95 vehicles.

Also, I'm going to add a vehicle driving in London in order to simulate a vehicle out of range.

**Comment by adamlukemooney** [comment]
@nicolasiensen Let's do it together 👍  We can definitely do this in a quick automated fashion.

**Comment by nicolasiensen** [comment]
@adamlukemooney could you review it again?

**Review by adamlukemooney — APPROVED** [review]

**Pull request merged**
