### PR TITLE
Combine challenges

### PR DESCRIPTION
**Pull request by tbueno**
Merge the different code challenges we have for candidates in a single repository. This will allow us to easily control the different variations we create and will be one step towards standardising our challenges per role instead of per team.

I decided to use this repository as the one to be the centralised (and soon to be renamed `d2d-code-challenges` or something similar because it was the one that had already 2 challenges in it.

So far, i moved the following challenges:
- https://github.com/door2door-io/data-engineer-challenge
- https://github.com/door2door-io/web-dev-code-challenge

I have not moved https://github.com/door2door-io/mi-code-challenge because I did not know how to called it in a way that I wouldn't be confused with the data-engineer one.  We can discuss whether it make sense to combine them somehow.

For https://github.com/door2door-io/data-engineer-code-challenge, i really want us to stop using it because: 

a) There is another challenge been used at the moment by MI
b) It touches the exact type of candidate that the https://github.com/door2door-io/data-engineer-challenge

Tell me what you think about this proposal. There also another option of moving each challenge to its own folder inside this repo.

### CODE REVIEW

**Comment by mariamrf** [comment]
If the challenges don't share any resources or solve the same general problems (I only skimmed through them so maybe I don't have the full picture here), in my opinion it would be better if there were separate folders for each challenge (inside this repo still).

If they're in separate folders we can also add the MI code challenge and combine (or not!) with the data engineer challenge in a separate step. What do you think?

**Comment by adamlukemooney** [comment]
I would consider a structure like:

```
- README.md (links to each of the challenge descriptions)
- challenges
    - FULLSTACK.md
    - BACKEND.md
    - DATA.md
    - WEB.md
    - MI.md
- resources
    - driver_simulator
      > code relating to the driver simulator used in fullstack + backend challenges
    - sample_data
      > data files for the data challenge
```

This will hide away the challenge-specific resources from candidates when they first open the repo, until they are directed specifically to the resource within the challenge descriptions, and hence might be less overwhelming.

What do you think?

**Comment by nicolasiensen** [comment]
Both suggestions from @mariamrf and @adamlukemooney sound good to me.

**Comment by osule** [comment]
I like to suggest a structure like the following based off @adamlukemooney 's
 .
├── FULLSTACK
│   ├── README.md
│   └── resources
├── BACKEND
├── DATA
├── WEB
├── MI
└── [shared-resources]

This has each role with its own `resources` folder tailored for that challenge.
Depending on whether resource files are shared, we can create a `shared-resources` folder to contain them. Symlinks in the challenge resources folder can be had to them.

What are your thoughts?

**Comment by tbueno** [comment]
i've used a combination of @osule's and @adamlukemooney's suggestions and moved each challenge to its own folder. Also, the driver simulator was moved to a shared resource folder.

**Review by adamlukemooney — APPROVED** [review]

**Pull request merged**
